"""Paths to bundled data files (rate limits, sectors, postcodes).

These files live next to this module so they are always available when the
package is installed as a wheel (no reliance on the project-root layout).
"""

from pathlib import Path

_LIB = Path(__file__).parent

PER_HOST_TOML = _LIB / "per-host.toml"
SECTORS_TOML = _LIB / "sectors.toml"
POSTCODES_TOML = _LIB / "postcodes.toml"
#: Generated by scripts/generate_nace_labels.py from a KBO Open Data ZIP.
NACE_LABELS_TOML = _LIB / "nace_labels.toml"
#: Ordered city rotation for the nightly scrape.
SCRAPE_CITIES_TOML = _LIB / "scrape_cities.toml"
