"""Regenerate ``src/scraper/lib/nace_labels.toml`` from a KBO Open Data ZIP.

The ZIP ships a ``code.csv`` holding the official NACE descriptions
(``Category, Code, Language, Description``). Those labels are static reference data —
they change only when a new NACE version is published — so they are extracted once into
a bundled TOML rather than staged into the database. Staging tables are UNLOGGED and are
emptied by crash recovery, which would silently blank the exported column.

Usage:
    uv run python scripts/generate_nace_labels.py KBO_zip/KboOpenData_*.zip
    uv run python scripts/generate_nace_labels.py <zip> --lang FR
"""

from __future__ import annotations

import argparse
import csv
import io
import sys
import zipfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_OUT = _ROOT / "src" / "scraper" / "lib" / "nace_labels.toml"

#: Every NACE version present in the observations. 2003 and 2008 hold far fewer
#: companies than 2025, but omitting them would leave those rows with a blank label.
_CATEGORIES = ("Nace2003", "Nace2008", "Nace2025")


def _toml_escape(value: str) -> str:
    """Escape a string for a TOML basic string (backslash first, then quote)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def extract_labels(zip_path: Path, lang: str) -> dict[str, dict[str, str]]:
    """Return ``{category: {code: description}}`` for *lang* from the ZIP's code.csv."""
    out: dict[str, dict[str, str]] = {c: {} for c in _CATEGORIES}
    with zipfile.ZipFile(zip_path) as z, z.open("code.csv") as fh:
        for row in csv.DictReader(io.TextIOWrapper(fh, "utf-8")):
            category = row["Category"]
            if category in out and row["Language"] == lang:
                description = row["Description"].strip()
                if description:
                    out[category][row["Code"]] = description
    return out


def render_toml(labels: dict[str, dict[str, str]], *, zip_name: str, lang: str) -> str:
    """Render the label map as TOML, one section per NACE version."""
    lines = [
        "# Generated by scripts/generate_nace_labels.py -- do not edit by hand.",
        f"# Source: {zip_name} (code.csv), language {lang}.",
        "# Regenerate when a new NACE version ships.",
    ]
    for category in _CATEGORIES:
        section = labels[category]
        lines.append("")
        lines.append(f"[{category.lower()}]")
        for code in sorted(section):
            lines.append(f'"{code}" = "{_toml_escape(section[code])}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("zip_path", type=Path, help="Path to a KboOpenData_*.zip")
    parser.add_argument("--lang", default="NL", choices=["NL", "FR"], help="Label language")
    parser.add_argument("--out", type=Path, default=_OUT, help="Output TOML path")
    args = parser.parse_args()

    if not args.zip_path.exists():
        print(f"No such ZIP: {args.zip_path}", file=sys.stderr)
        return 2

    labels = extract_labels(args.zip_path, args.lang)
    total = sum(len(v) for v in labels.values())
    if total == 0:
        print(f"No labels found for language {args.lang}", file=sys.stderr)
        return 1

    args.out.write_text(
        render_toml(labels, zip_name=args.zip_path.name, lang=args.lang), encoding="utf-8"
    )
    for category in _CATEGORIES:
        print(f"  {category}: {len(labels[category])} labels")
    print(f"Wrote {total} labels to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
